### ISSUE TITLE
async functions

### ISSUE THREAD

**Issue by gizmo-ds** [m-hayabusa/send_text_to_vrc#1]
publishは、async functionsの方が使いやすいかもしれません。
My Japanese is not good, so I used a translator 😢

https://github.com/project-vrcat/send_text_to_vrc/commit/f55597d06229bad71f86c4d5b5114462d4267d17

```typescript
await send_text_to_vrc.publish([input], outputFile, tempDirPrefix);
const video = fs.readFileSync(outputFile);
res.setHeader("content-type", "video/webm");
res.send(video);
```

**Comment by m-hayabusa** [comment]
確かにasyncのほうが便利そうなのでmergeします、ありがとうございます
